// app/src/components/molecules/ChatMessage.tsx
import { tv } from 'tailwind-variants';
import { MessageResponseRole } from '@/api/generated/server.client';
import { Text } from '@/components/atoms/Text';
import { cn } from '@/utils/helpers/cn';

interface ChatMessageProps {
	message: string;
	role: MessageResponseRole;
}

const containerVariants = tv({
	base: 'flex w-full',
	variants: {
		role: {
			[MessageResponseRole.USER]: 'justify-start',
			[MessageResponseRole.ASSISTANT]: 'justify-end',
			[MessageResponseRole.TOOL]: 'justify-end'
		}
	}
});

const messageVariants = tv({
	base: 'p-2 rounded-lg max-w-[80%]',
	variants: {
		role: {
			[MessageResponseRole.USER]: 'bg-primary text-primary-content',
			[MessageResponseRole.ASSISTANT]: 'bg-secondary text-secondary-content',
			[MessageResponseRole.TOOL]: 'bg-accent text-accent-content'
		}
	}
});

export const ChatMessage = ({ message, role }: ChatMessageProps) => {
	return (
		<div className={containerVariants({ role })}>
			<div className={cn(messageVariants({ role }))}>
				<Text variant="paragraph">{message}</Text>
			</div>
		</div>
	);
};

// app/src/lib/components/molecules/chat-message/index.svelte
<script lang="ts">
	import { tv } from 'tailwind-variants';
	import { Text } from '@/components/atoms/text';
	import { type Role, ROLES } from '@/schemas/api/chat';
	import { cn } from '@/utils/helpers/shadcn';

	interface Props {
		message: string;
		role: Role;
	}

	let { message, role }: Props = $props();

	const containerVariants = tv({
		base: 'flex w-full',
		variants: {
			role: {
				[ROLES.USER]: 'justify-start',
				[ROLES.ASSISTANT]: 'justify-end',
				[ROLES.TOOL]: 'justify-end'
			}
		}
	});

	const messageVariants = tv({
		base: 'p-2 rounded-lg max-w-[80%]',
		variants: {
			role: {
				[ROLES.USER]: 'bg-primary text-primary-content',
				[ROLES.ASSISTANT]: 'bg-accent text-accent-content',
				[ROLES.TOOL]: 'bg-accent text-accent-content'
			}
		}
	});
</script>

<div class={containerVariants({ role })}>
	<div class={cn(messageVariants({ role }))}>
		<Text variant="paragraph">{message}</Text>
	</div>
</div>
