// app/src/components/organisms/Chat.tsx
import { useState, useCallback } from 'react';
import { useMutation } from '@tanstack/react-query';
import { createMessage } from '@/api/messages';
import { ChatInput } from './ChatInput';
import { ChatMessages } from './ChatMessages';
import { useChatEvents } from '@/hooks/useChatEvents';
import type { MessageResponse } from '@/api/generated/server.client';

interface ChatProps {
  initialMessages?: MessageResponse[];
  chatId: string;
}

export const Chat = ({ initialMessages = [], chatId }: ChatProps) => {
  const [messages, setMessages] = useState<MessageResponse[]>(initialMessages);
  const [isPending, setIsPending] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const handleSSEMessage = useCallback((message: MessageResponse) => {
    setMessages((prev) => [...prev, message]);
    setIsPending(false);
    setErrorMessage(null);
  }, []);

  const handleSSEError = useCallback((error: string) => {
    setIsPending(false);
    setErrorMessage(error);
  }, []);

  useChatEvents(chatId, {
    onMessage: handleSSEMessage,
    onError: handleSSEError,
  });

  const mutation = useMutation({
    mutationFn: (content: string) => createMessage(chatId, { content }),
    onSuccess: (newMessage: MessageResponse) => {
      setMessages((prev) => [...prev, newMessage]);
      setIsPending(true);
      setErrorMessage(null);
    },
    onError: (error) => {
      setIsPending(false);
      throw error;
    },
  });

  return (
    <div className="grid h-full grid-rows-[1fr_auto]">
      <div className="overflow-y-auto">
        <ChatMessages messages={messages} isPending={isPending} errorMessage={errorMessage} />
      </div>
      <div className="flex justify-center">
        <ChatInput sendMessage={(message: string) => mutation.mutate(message)} />
      </div>
    </div>
  );
};

// app/src/lib/components/organisms/chat/index.svelte
<script lang="ts">
	import { createMutation } from '@tanstack/svelte-query';
	import { onDestroy } from 'svelte';
	import { create } from '@/api/messages';
	import { ChatInput } from '@/components/organisms/chat-input';
	import { ChatMessages } from '@/components/organisms/chat-messages';
	import { useChatEvents } from '@/hooks';
	import type { Message, MessageRequest } from '@/schemas/api';

	interface Props {
		initialMessages?: Message[];
		chatId: string;
	}

	let { initialMessages = [], chatId }: Props = $props();

	let messages = $state<Message[]>(initialMessages);
	let isPending = $state(false);
	let errorMessage = $state<string | null>(null);

	// Subscribe to real-time messages via SSE
	const chatEvents = useChatEvents(chatId, {
		onMessage: (message) => {
			// Add the AI response to messages
			messages.push(message);
			isPending = false;
			errorMessage = null;
		},
		onError: (error) => {
			// Handle worker/LLM errors
			isPending = false;
			errorMessage = error;
		}
	});

	// Cleanup SSE connection on component destroy
	onDestroy(() => {
		chatEvents.disconnect();
	});

	const mutation = createMutation(() => ({
		mutationFn: (payload: MessageRequest) => create({ id: chatId }, payload),
		onSuccess: (newMessage: Message) => {
			messages.push(newMessage);
			// Now waiting for AI response via SSE
			isPending = true;
			errorMessage = null;
		},
		onError: (error) => {
			isPending = false;
			throw error;
		}
	}));
</script>

<div class="grid h-full grid-rows-[1fr_auto]">
	<div class="overflow-y-auto">
		<ChatMessages {messages} {isPending} {errorMessage} />
	</div>

	<div class="flex justify-center">
		<ChatInput sendMessage={(message: string) => mutation.mutate({ content: message })} />
	</div>
</div>
