// app/src/lib/components/molecules/loading-screen/index.svelte
<script lang="ts">
	import { fade } from 'svelte/transition';
	import { LoadingSpinner } from '@/components/atoms/loading-spinner';
	import { Text } from '@/components/atoms/text';

	interface Props {
		title?: string;
	}

	let { title = 'Loading your workspace...' }: Props = $props();
</script>

<div
	out:fade={{ duration: 200 }}
	class="bg-base-100 fixed inset-0 z-9999 flex items-center justify-center"
>
	<div class="flex flex-col items-center gap-4">
		<LoadingSpinner class="text-primary size-12" />
		<Text variant="label" class="text-primary animate-pulse">{title}</Text>
	</div>
</div>

// app/src/components/molecules/LoadingScreen.tsx
import { LoadingSpinner } from '@/components/atoms/LoadingSpinner';
import { Text } from '@/components/atoms/Text';

interface LoadingScreenProps {
	title?: string;
}

export const LoadingScreen = ({ title = 'Loading your workspace...' }: LoadingScreenProps) => {
	return (
		<div className="bg-base-100 fixed inset-0 z-[9999] flex items-center justify-center">
			<div className="flex flex-col items-center gap-4">
				<LoadingSpinner className="text-primary size-12" />
				<Text variant="label" className="text-primary animate-pulse">
					{title}
				</Text>
			</div>
		</div>
	);
};
