// app/src/components/atoms/LoadingSpinner.tsx
import { Loader } from 'lucide-react';
import { cn } from '@/utils/helpers/cn';

interface LoadingSpinnerProps {
	className?: string;
}

export const LoadingSpinner = ({ className }: LoadingSpinnerProps) => {
	return (
		<Loader role="status" aria-label="Loading" className={cn('size-4 animate-spin', className)} />
	);
};

// app/src/lib/components/atoms/loading-spinner/index.svelte
<script lang="ts">
	import LoaderIcon from '@lucide/svelte/icons/loader';
	import type { ComponentProps } from 'svelte';
	import { cn } from '$lib/utils/helpers/shadcn';

	type Props = ComponentProps<typeof LoaderIcon>;

	let { class: className, ...restProps }: Props = $props();
</script>

<LoaderIcon
	role="status"
	aria-label="Loading"
	class={cn('size-4 animate-spin', className)}
	{...restProps}
/>
