// app/src/lib/components/atoms/text/index.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { tv } from 'tailwind-variants';
	import { cn } from '@/utils/helpers/shadcn';

	type Variant = keyof typeof ELEMENTS;

	const ELEMENTS = {
		heading: 'h1',
		subHeading: 'h2',
		label: 'label',
		paragraph: 'p'
	} as const;

	interface Props {
		variant: Variant;
		children: Snippet;
		class?: string;
	}

	const variants = tv({
		variants: {
			variant: {
				heading: 'text-2xl font-bold',
				subHeading: 'text-xl font-bold',
				label: 'text-sm font-medium',
				paragraph: 'text-base font-normal'
			}
		}
	});

	let { variant, children, class: className }: Props = $props();
</script>

<svelte:element this={ELEMENTS[variant]} class={cn(variants({ variant }), className)}>
	{@render children()}
</svelte:element>

// app/src/components/atoms/Text.tsx
import { createElement, type ReactNode } from 'react';
import { tv } from 'tailwind-variants';
import { cn } from '@/utils/helpers/cn';

type Variant = 'heading' | 'subHeading' | 'label' | 'paragraph';

const ELEMENTS: Record<Variant, string> = {
  heading: 'h1',
  subHeading: 'h2',
  label: 'label',
  paragraph: 'p',
};

const variants = tv({
  variants: {
    variant: {
      heading: 'text-2xl font-bold',
      subHeading: 'text-xl font-bold',
      label: 'text-sm font-medium',
      paragraph: 'text-base font-normal',
    },
  },
});

interface TextProps {
  variant: Variant;
  children: ReactNode;
  className?: string;
}

export const Text = ({ variant, children, className }: TextProps) => {
  return createElement(
    ELEMENTS[variant],
    { className: cn(variants({ variant }), className) },
    children,
  );
};
